version: "3.9"
services:
  notaryshot-adapter:
    image: "chainhackers/quantumoracle-adapter:${TAG}"
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 600s
  redis:
    image: "redis:alpine"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  chrome:
    image: "browserless/chrome:latest"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
